# Workflow Name
name: Release Process

on:
  pull_request:
    branches:
      - main

jobs:
  # Job
  generate-release:                 # Job id
    name: Create GitHub Release     # Job name
    runs-on: ubuntu-latest          # Runner
    steps:
    - name: Checkout Repository     # Step1
      uses: actions/checkout@v4     # Actions
      
    - name: Run release code        # Step2
      run: |
        echo 'hi'

    - name: fail
      run: exit 1
